[project]
name = 'DecentralizedDelivery'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.DecentralizedDelivery]
path = 'contracts/DecentralizedDelivery.clar'
clarity_version = 3
epoch = 3.1
[contracts.RouteOptimization]
path = 'contracts/RouteOptimization.clar'
clarity_version = 3
epoch = 3.1
[contracts.DeliveryNotifications]
path = 'contracts/DeliveryNotifications.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
